apiVersion: v1
kind: Pod
metadata:
  name: queue
spec:
  containers:
  - name: producer
    image: allingeek/ch6_ipc
    command: ["./ipc", "-producer"]
  - name: consumer
    image: allingeek/ch6_ipc
    command: ["./ipc", "-consumer"]
  restartPolicy: Never


## Como testar?
# kubectl logs queue -c producer
# kubectl logs queue -c consomer