apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    name: my-sample-pod

spec:
  containers:
  - name: sample-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
