apiVersion: v1
kind: PersistentVolume
metadata:
  name: google-main-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: google

# Não pode ser utilizado dinamicamente