apiVersion: v1
kind: Pod
metadata:
  name: pod-with-dynamic-volume
spec:
  containers:
  - name: pvc-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /app/files
        name: pv

  volumes:
  - name: pv
    persistentVolumeClaim:
      claimName: google-pvc