apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: thiagoanselme/nginx-com-vim
    name: test-container
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}