apiVersion: v1
kind: Pod
metadata:
  name: anselme-gce-pod
spec:
  containers:
  - image: thiagoanselme/nginx-com-vim
    name: test-container1
    volumeMounts:
    - mountPath: /appx
      name: test-volume-full
  volumes:
  - name: test-volume-full
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: anselme-disk
      fsType: ext4
      # gcloud compute disks create --size=1GB --zone=us-central1-a anselme-disk


