apiVersion: v1
kind: Pod
metadata:
  name: anselme-gce-pod
spec:
  containers:
  - image: thiagoanselme/nginx-com-vim
    name: test-container1
    volumeMounts:
    - mountPath: /appx
      name: test-volume-full
  volumes:
  - name: test-volume-full
    gcePersistentDisk:
      pdName: anselme-disk
      fsType: ext4


