apiVersion: v1
kind: Pod
metadata:
  name: test-pd12
spec:
  containers:
  - image: debian
    name: test-container
    command: ["/bin/bash", "-c"]
    args:
      - while true; do
          sleep 60; 
        done    
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: DirectoryOrCreate