apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  USER: "dGhpYWdvCg=="
  PASSWORD: "MTIzNDU2Cg=="

---

apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: nginx
    image: thiagoanselme/nginx-com-vim
    volumeMounts:
    - name: secret
      mountPath: "/app/secret"
      readOnly: true
  volumes:
  - name: secret
    secret:
      secretName: my-secret
      optional: false # default setting; "mysecret" must exist
