apiVersion: v1
kind: Pod
metadata:
  name: gce

spec:
  restartPolicy: Never
  volumes:
  - name: test-volume-full
    gcePersistentDisk:
      pdName: anselme-disk
      fsType: ext4

  containers:
  - name: container-one
    image: debian
    volumeMounts:
    - mountPath: /appx
      name: test-volume-full    
    command: ["/bin/bash", "-c"]
    args:
      - while true; do
          sleep 60; 
        done

        

  - name: container-two
    image: debian
    command: ["/bin/bash", "-c"]
    args:
      - while true; do
          sleep 60; 
        done

