apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    name: two-containers
    anotherlabel: another-value

spec:
  containers:
  - name: container-one
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

  - name: container-two
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 81
