# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none

---
# Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: google-pvc
spec:
  accessModes:
  # - ReadOnlyMany
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: google

---
# Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-pvc
            

      volumes:
      - name: mysql-pvc
        persistentVolumeClaim:
          claimName: google-pvc