apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  selector:
    app: goserver
  ports:
  - port: 80            # porta que o service expoe para fora
    targetPort: 9001    # porta que o pod expoe
    protocol: TCP
