apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - port: 80                # outsite port: valid outsite the cluster on the internet;
      targetPort: 9001        # container port
      protocol: TCP
      nodePort: 30001         # internal cluster port, acessible for all nodes on the cluster