apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  type: LoadBalancer
  selector:
    app: goserver
  ports:
    - port: 80                # porta que o service expor para dentro do cluster
      targetPort: 9001        # porta que o pod expoe para fora
      protocol: TCP
      nodePort: 30001         # porta que o service expoe em todos os nodes do cluster