apiVersion: v1
kind: Service
metadata:
  name: goserver
spec:
  type: NodePort
  selector:
    app: goserver
  ports:
    - port: 80            # outsite port: valid only on the cluster;
      targetPort: 9001    # container port
      # Optional field
      nodePort: 30001     # internal cluster port, acessible for all nodes on the cluster
      protocol: TCP