apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app:ingress-creator
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingressClasses","ingresses"]
  verbs: ["create","get","list","update"]