apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app:ingress-creator-rb
subjects:
- kind: ServiceAccount
  name: anselme-account
  namespace: prod
roleRef:
  kind: ClusterRole
  name: app:ingress-creator
  apiGroup: rbac.authorization.k8s.io