apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount
  name: anselme-account
  namespace: default
roleRef:
  kind: Role
  name: server-read
  apiGroup: rbac.authorization.k8s.io