apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: server-read
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","watch","list"]

- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","watch","list"]

  