apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: access-to-production-database
  namespace: database

spec:
  podSelector:
    matchLabels:
      environment: database
  policyTypes:
    - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          myspace: production