apiVersion: v1
kind: Pod
metadata:
  name: meupod
  labels:
    name: meupod
spec: 
  containers:
  - name: meupod
    image: nginx
    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      periodSeconds: 5             
      failureThreshold: 1          
      timeoutSeconds: 1            
      successThreshold: 1   