apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: my-pod
spec: 
  containers:
  - name: mypod
    image: nginx
    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      periodSeconds: 5             
      failureThreshold: 1          
      timeoutSeconds: 1            
      successThreshold: 1   