apiVersion: v1
kind: Pod
metadata:
  name: meupod3
  labels:
    name: meupod3
spec: 
  containers:
  - name: meupod3
    image: nginx
    
    startupProbe:
      httpGet:
        path: /healthz
        port: 80
      periodSeconds: 5
      failureThreshold: 3          

    readinessProbe:
      httpGet:
        path: /healthz
        port: 80
      periodSeconds: 5             
      failureThreshold: 2          
      timeoutSeconds: 3            

    livenessProbe:
      httpGet:
        path: /healthz
        port: 80
      periodSeconds: 10             
      failureThreshold: 2          
      timeoutSeconds: 10            
  

    