apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:                                        
    kubernetes.io/ingress.class: "nginx"              
    cert-manager.io/cluster-issuer: "lets-encrypt"    
    ingress.kubernetes.io/force-ssl-redirect: "true"  

spec:
  rules:
  - host: "ingress.website.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: goserver
            port: 
              number: 80
  tls:
  - hosts:
    - "ingress.website.com"  
    secretName: "lets-encrypt-certificate"

