apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:                                        
    kubernetes.io/ingress.class: "nginx"              

spec:
  rules:
  - host: "ingress.website.com"
    http:
      paths:
      - pathType: Prefix
        path: "/test"
        backend:
          service:
            name: goserver
            port: 
              number: 80

