apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
  namespace: cert-manager

spec:
  acme:                                                               # Issuer
    server: https://acme-v02.api.letsencrypt.org/directory            # url of cartificate issuer
    email: certificate-email@mail.com                                 # reference mail to the certificates
    privateKeySecretRef:
      name: lets-encrypt-certificate                                  # Name os secret key certificate
    solvers:
    - http01:
        ingress:
          class: nginx                                                # Who is allow to use that one. It depends on the 'Annotation' on Ingress


# The ingress needs to have these configuration lines
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-host
#   annotations:                                      
#     kubernetes.io/ingress.class: "nginx"                            # It is obligatory