apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
  namespace: cert-manager

spec:
  acme:                                                         # Definição de quem vai emitir os certificados
    server: https://acme-v02.api.letsencrypt.org/directory      # URL da emissora
    email: thiago@anselme.com.br                                # e-mail de referência para o certificado
    privateKeySecretRef:
      name: lets-encrypt-certificate                            # nome da chave privada do certificado
    solvers:
    - http01:
        ingress:
          class: nginx                                            # quem no cluster pode utilizar. Isso depende da Annotation no Ingress

## Essas anotations que precisam estar relacionadas com o solver
#
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ingress-host
#   annotations:                                        ## Sistemas que consomem desse ingress podem utilizar esse anotation para alguma funcionalidade
#     kubernetes.io/ingress.class: "nginx"              ## podem existir outros Ingress