apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: "nginx"
    spec:
      containers:
        - name: nginx 
          image: nginx
          envFrom:
            - configMapRef:
                name: "simple-configmap"
          volumeMounts:
            - mountPath: "/app/conf"
              name: conf-volume

      volumes:
        - name: conf-volume
          configMap:
            name: simple-configmap
            items: 
            - key: databasename
              path: "config-file"