apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment             
    name: my-nginx
  minReplicas: 1                 
  maxReplicas: 10                
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
  metrics:                       
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 3   