apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment             # a quem esse destina esse HPA
    name: meunginx
  minReplicas: 1                  # mínimo de réplicas. O adequado é 2 ou 3
  maxReplicas: 10                 # máximo de répllicas. Não existe limite adequad
  behavior:
    scaleDown:
      policies:
      - type: Pods
        value: 1
        periodSeconds: 30
  metrics:                       # Qual métrica será utilizada?
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 3   # Consumo acim de 15% de CPU